# First stage image labelled as node
FROM node:12.0.0 as node

# Building Angular app
WORKDIR /usr/src/app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build -- --prod

# This image will be used for creating container
FROM nginx:1.13.12-alpine
COPY --from=node /usr/src/app/dist/Artemis /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
